################################################################################
# Create Time Series Summaries and Current Status
#
# This script creates a table that captures the current open science status of all preprints in the database.  Not to be confused with *lifecycle* open science status, the features generated by this script captures whether or a preprint currently meets a minimum set of criteria to be considered an Open Science Preprint (OSP).  See `R/criteria.R` for the full set of criteria.
#
# Input tables:
#   - data/preprint.parquet (scripts/dataprep/preprint.r)
#   - data/preprint_visibility.parquet (scripts/dataprep/preprint-events.r)
#   - data/preprint_spam.parquet (scripts/dataprep/preprint-events.r)
#
# Output files:
#   - /data/preprint_tsmonthly.parquet
#   - /data/preprint_providers_tsmonthly.parquet
#   - /data/preprint_current.parquet
################################################################################

# Packages
library(arrow)
library(dbplyr)
library(dplyr)
library(glue)
library(lubridate)
library(stringr)
library(tidyr)
library(purrr)

# Modules
box::use(
  R / connect[open_parquet],
  R /
    database[
      cumulative_logged_actions,
      last_logged_action,
      ppt_resource_status,
      ppt_recipe_status_summed,
      ppt_recipe_status_typed
    ],
  R / helpers[tidyup],
  R / parameters[DATES],
  R / criteria[CRITERIA_OSP]
)

# I/O
PQROOT <- "data/preprint"
PQSUFFIX <- "tsmonthly.parquet"
PATH_ALL <- glue("{PQROOT}_{PQSUFFIX}")
PATH_PRV <- glue("{PQROOT}_providers_{PQSUFFIX}")
PATH_CUR <- glue("{PQROOT}_current.parquet")

FACETS <- rlang::expr(provider)


# DATA PREP --------------------------------------------------------------------
# Status datasets
ppt_main <- open_parquet("data", "preprint")
ppt_visibility <- open_parquet("data", "preprint_visibility")
ppt_spam <- open_parquet("data", "preprint_spam")
ppt_supplements <- open_parquet("data", "preprint_supplements")

# Combine statuses
ppttime_tbl <- ppt_main |>
  select(
    preprint_id,
    created,
    date_withdrawn,
    date_published,
    deleted,
    machine_state,
    provider,
    has_data_links,
    has_prereg_links,
    !!FACETS
  ) |>
  left_join(
    ppt_visibility,
    by = "preprint_id",
    relationship = "many-to-many"
  ) |>
  left_join(ppt_spam, by = "preprint_id", relationship = "many-to-many")

# # Add linked supplements and registrations
# ppttime_tbl <- ppttime_tbl |>
#   left_join(ppt_supplements, by = "preprint_id", relationship = "many-to-many")

# Resource data
ppt_resources <- open_parquet("data", "preprint_resources")


# FUNCTIONS --------------------------------------------------------------------
# Generate the status of each preprint along criteria of interest at a given date
create_status_table <- function(date) {
  # Prep data sources
  snapshot <- ppttime_tbl |>
    filter(created <= date)
  status_main <- snapshot |>
    select(
      preprint_id,
      created,
      date_withdrawn,
      date_published,
      machine_state,
      deleted,
      !!FACETS
    ) |>
    distinct(preprint_id, .keep_all = TRUE)
  status_vis <- snapshot |>
    last_logged_action(
      visibility_status_date,
      visibility_status,
      date,
      preprint_id
    ) |>
    rename(visibility = status)
  status_spam <- snapshot |>
    last_logged_action(spam_status_date, spam_status, date, preprint_id) |>
    rename(spam = status)

  # # Linked supplements
  # supplements_at_date <- snapshot |>
  #   filter(supplement_status_date < date) |>
  #   summarize(
  #     .by = preprint_id,
  #     n_supplements = sum(supplement_status == "add-supplement", na.rm = TRUE),
  #     n_removals = sum(supplement_status == "remove-supplement", na.rm = TRUE)
  #   ) |>
  #   mutate(
  #     has_supplement = ifelse(n_supplements - n_removals > 0, 1, 0)
  #   )

  # Compute status
  status_at_date <- status_main |>
    left_join(status_vis, by = "preprint_id") |>
    left_join(status_spam, by = "preprint_id") |>
    # left_join(supplements_at_date, by = "preprint_id") |>
    mutate(
      is_open = ifelse(!!CRITERIA_OSP$open, 1, 0),
      is_nondeprecated = ifelse(!!CRITERIA_OSP$nondeprecated, 1, 0),
      is_authentic = ifelse(!!CRITERIA_OSP$authentic, 1, 0)
    )
  return(status_at_date)
}

#' Compute the lifecycle open status of each preprint at a given date
compute_los_status <- function(date, method = c("typed", "summed")) {
  # Get statuses
  status_at_date <- create_status_table(date)

  # Get resources
  resources_at_date <- ppt_resource_status(
    ppt_resources,
    date,
    preprint_id,
    resource_type
  )
  # Apply lifecycle open science recipe to get resources
  if (method[1] == "typed") {
    recipe_at_date <- resources_at_date |>
      ppt_recipe_status_typed()
  }
  if (method[1] == "summed") {
    recipe_at_date <- resources_at_date |>
      ppt_recipe_status_summed()
  }

  # Join
  status_at_date |>
    left_join(recipe_at_date, by = "preprint_id") |>
    mutate(
      n_outputs = ifelse(is.na(n_outputs), 0, n_outputs),
      n_plans = ifelse(is.na(n_plans), 0, n_plans)
    )
}

#' Summarize the lifecycle open status all preprint at a given date
los_summary <- function(status_tbl, ...) {
  status_tbl |>
    summarise(
      .by = c(...),
      n_total = n(),
      # Openness components
      n_public = sum(visibility == "public"),
      # Non-deprecated components
      n_accepted = sum(machine_state == "accepted"),
      n_published = sum(!is.na(date_published)),
      n_not_deleted = sum(!is.na(deleted)),
      n_not_withdrawn = sum(!is.na(date_withdrawn)),
      # LOS Outcome (i.e., open, non-deprecated, and authentic)
      n_open = sum(is_open == 1),
      n_not_deprecated = sum(is_nondeprecated == 1),
      n_authentic = sum(is_authentic == 1),
      n_open_notdep = sum(is_open == 1 & is_nondeprecated == 1),
      n_open_auth = sum(is_open == 1 & is_authentic == 1),
      n_notdep_auth = sum(is_authentic == 1 & is_nondeprecated == 1),
      # Full LOS
      n_los_outcome = sum(
        is_open == 1 & is_nondeprecated == 1 & is_authentic == 1,
        na.rm = TRUE
      ),
      # LOS Relationships
      n_los_plans = sum(n_plans > 0, na.rm = TRUE),
      n_los_outputs = sum(n_outputs > 0, na.rm = TRUE),
      # Full LOS
      n_los_complete = sum(
        is_open == 1 &
          is_nondeprecated == 1 &
          is_authentic == 1 &
          n_plans > 0 &
          n_outputs > 0,
        na.rm = TRUE
      )
    )
}

# Wrapper to compute summaries for all dates
compute_all_summaries <- function(
  dates,
  grp = NULL,
  method = c("typed", "summed")
) {
  purrr::map(
    dates,
    ~ compute_los_status(.x, method) |>
      los_summary({{ grp }}) |>
      collect(),
    .progress = TRUE
  ) |>
    tidyup(dates, "date")
}


# COMPUTE ----------------------------------------------------------------------
# Current status
s <- Sys.time()
current_status <- create_status_table(DATES[length(DATES)]) |>
  mutate(
    is_osp = ifelse((is_open + is_nondeprecated + is_authentic) / 3 == 1, 1, 0)
  ) |>
  collect()
write_parquet(current_status, PATH_CUR)
elapsed <- Sys.time() - s
print(elapsed)

# Aggregate summaries
s <- Sys.time()
all_summaries <- compute_all_summaries(DATES)
write_parquet(all_summaries, PATH_ALL)
elapsed <- Sys.time() - s
print(elapsed)

# Summaries by provider
s <- Sys.time()
all_summaries_prv <- compute_all_summaries(DATES, provider)
write_parquet(all_summaries_prv, PATH_PRV)
elapsed <- Sys.time() - s
print(elapsed)
