################################################################################
# Create Open Science Registration Status
#
# This script creates a table that captures the current open science status of all registrations in the database.  Not to be confused with *lifecycle* open science status, the field generated by this script captures whether or a registration currently meets a minimum set of criteria to be considered an Open Science Registration (OSR).  See `R/criteria.R` for the full set of criteria.
#
# Input tables:
#   - data/registration.parquet (scripts/dataprep/registration.r)
#   - data/registration_visibility.parquet (scripts/dataprep/registration-events.r)
#   - data/registration_embargo.parquet (scripts/dataprep/registration-events.r)
#   - data/registration_retraction.parquet (scripts/dataprep/registration-events.r)
#   - data/registration_spam.parquet (scripts/dataprep/registration-events.r)
#
# Output file:
#   - /data/registration_osr.parquet
################################################################################

# Packages
library(arrow)
library(dbplyr)
library(dplyr)
library(glue)
library(lubridate)
library(stringr)
library(tidyr)
library(purrr)

# Modules
box::use(
  R / connect[open_parquet],
  R / parameters[DATES]
)

# I/O
PATHOUT <- "data/registration_osr.parquet"


# DATA PREP -----------------------------------------------------------------
# Status datasets
reg_main <- open_parquet("data", "registration")
reg_visibility <- open_parquet("data", "registration_visibility")
reg_embargo <- open_parquet("data", "registration_embargo")
reg_retracted <- open_parquet("data", "registration_retraction")
reg_spam <- open_parquet("data", "registration_spam")

# Combine statuses
regtime_tbl <- reg_main |>
  select("node_id", "created", "registered_date", "deleted") |>
  left_join(reg_visibility, by = "node_id", relationship = "many-to-many") |>
  left_join(reg_embargo, by = "node_id", relationship = "many-to-many") |>
  left_join(reg_retracted, by = "node_id", relationship = "many-to-many") |>
  left_join(reg_spam, by = "node_id", relationship = "many-to-many")


# COMPUTE -------------------------------------------------------------------
# Compute whether registration is OSR at most recent date
s <- Sys.time()
osr_status <- create_status_table(regtime_tbl, DATES[length(DATES)]) |>
  mutate(
    is_osr = ifelse((is_open + is_nondeprecated + is_authentic) / 3 == 1, 1, 0)
  ) |>
  select(node_id, is_osr)
write_parquet(osr_status, PATH_OSR)
elapsed <- Sys.time() - s
print(elapsed)
